/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/admin/get_admin_settings.php": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Admin Settings
         * @description Retrieve admin settings from the Wallos application.
         */
        get: {
            parameters: {
                query: {
                    /** @description API key of the user. */
                    apiKey: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Successful response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description Indicates whether the request was successful. */
                            success?: boolean;
                            /** @description The title of the response. */
                            title?: string;
                            admin_settings?: {
                                /** @description Indicates if registrations are open (1 for true, 0 for false). */
                                registrations_open?: number;
                                /** @description The maximum number of users allowed. */
                                max_users?: number;
                                /** @description Indicates if email verification is required (1 for true, 0 for false). */
                                require_email_verification?: number;
                                /**
                                 * Format: uri
                                 * @description The server URL.
                                 */
                                server_url?: string;
                                /** @description The SMTP address for sending emails. */
                                smtp_address?: string;
                                /** @description The port for the SMTP server. */
                                smtp_port?: number;
                                /** @description The username for SMTP authentication. */
                                smtp_username?: string;
                                /** @description The password for SMTP authentication. */
                                smtp_password?: string;
                                /**
                                 * Format: email
                                 * @description The email address used as the sender.
                                 */
                                from_email?: string;
                                /** @description The encryption method for SMTP (e.g., tls, ssl). */
                                encryption?: string;
                                /** @description Indicates if login is disabled (1 for true, 0 for false). */
                                login_disabled?: number;
                                /** @description The latest version of the application. */
                                latest_version?: string;
                                /** @description Indicates if update notifications are enabled (1 for true, 0 for false). */
                                update_notification?: number;
                                /** @description Indicates if OIDC OAuth logins are active (1 for true, 0 for false). */
                                oidc_oauth_enabled?: number;
                                /** @description A comma-separated list of hostnames or IP addresses allowed for local webhook notifications to mitigate SSRF. */
                                local_webhook_notifications_allowlist?: string;
                            };
                            /** @description Warning messages or additional information. */
                            notes?: string[];
                        };
                    };
                };
                /** @description Unauthorized - Invalid API Key */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example false */
                            success?: boolean;
                            /** @example Unauthorized */
                            title?: string;
                            /**
                             * @example [
                             *       "Invalid API Key"
                             *     ]
                             */
                            notes?: string[];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/set_admin_settings.php": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Save Admin Settings
         * @description Update global admin settings for the application. Requires user ID 1 (Admin role).
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/x-www-form-urlencoded": {
                        /** @description The Admin's Wallos API Key. */
                        api_key: string;
                        /**
                         * @description '1' if registrations are open, '0' if closed.
                         * @enum {integer}
                         */
                        registrations_open?: 0 | 1;
                        /** @description Maximum allowed users in the system. */
                        max_users?: number;
                        /**
                         * @description '1' if email verification is required, '0' otherwise.
                         * @enum {integer}
                         */
                        require_email_verification?: 0 | 1;
                        /**
                         * Format: uri
                         * @description The base URL of this Wallos instance (required if email verification is enabled).
                         */
                        server_url?: string;
                        /** @description SMTP mail server hostname. */
                        smtp_address?: string;
                        /** @description SMTP port (e.g. 587, 465). */
                        smtp_port?: number;
                        /** @description SMTP mail username. */
                        smtp_username?: string;
                        /** @description SMTP mail password. */
                        smtp_password?: string;
                        /**
                         * Format: email
                         * @description Sender email address.
                         */
                        from_email?: string;
                        /**
                         * @description Encryption type for mail.
                         * @enum {string}
                         */
                        encryption?: "tls" | "ssl" | "none";
                        /**
                         * @description '1' to disable password login (only allowed if registrations are closed and user count is 1).
                         * @enum {integer}
                         */
                        login_disabled?: 0 | 1;
                        /**
                         * @description '1' to check and notify about application updates.
                         * @enum {integer}
                         */
                        update_notification?: 0 | 1;
                        /**
                         * @description '1' to enable OIDC OAuth 2.0 logins.
                         * @enum {integer}
                         */
                        oidc_oauth_enabled?: 0 | 1;
                        /** @description Comma-separated list of hostnames or IP addresses allowed for local webhook execution (SSRF mitigation). */
                        local_webhook_notifications_allowlist?: string;
                    };
                };
            };
            responses: {
                /** @description Successful operation. Returns JSON. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description True if settings were saved. */
                            success?: boolean;
                            /** @description Brief status title. */
                            title?: string;
                            /** @description Description of the result or error. */
                            message?: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/set_disable_password_login.php": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Disable Password Login
         * @description Controls whether standard password-based login is allowed or if OIDC is strictly enforced. Requires user ID 1 (Admin role).
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/x-www-form-urlencoded": {
                        /** @description The Admin's Wallos API Key. */
                        api_key: string;
                        /**
                         * @description '1' to disable standard password logins, '0' to enable standard password logins.
                         * @enum {string}
                         */
                        disable: "0" | "1";
                    };
                };
            };
            responses: {
                /** @description Operation processed successfully. Returns JSON. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description True if settings were updated. */
                            success?: boolean;
                            /** @description Brief status title. */
                            title?: string;
                            /** @description Description of the result or error. */
                            message?: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/get_oidc_settings.php": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get OIDC Settings
         * @description Retrieve the global OpenID Connect (OIDC) authentication settings. Requires user ID 1 (Admin role).
         */
        get: {
            parameters: {
                query: {
                    /** @description The Admin's Wallos API Key. */
                    api_key: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Successful retrieval of OIDC settings. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "success": true,
                         *       "title": "oidc_settings",
                         *       "oidc_settings": {
                         *         "name": "Authentik",
                         *         "client_id": "CJMLcyyS94cUMXkitNZuokayArnn23TXxpeUv48E",
                         *         "client_secret": "********",
                         *         "authorization_url": "https://auth.example.com/application/o/authorize/",
                         *         "token_url": "https://auth.example.com/application/o/token/",
                         *         "user_info_url": "https://auth.example.com/application/o/userinfo/",
                         *         "redirect_url": "http://localhost:80/wallos",
                         *         "logout_url": "https://auth.example.com/application/o/wallos/end-session/",
                         *         "user_identifier_field": "sub",
                         *         "scopes": "openid email profile",
                         *         "auth_style": "auto",
                         *         "created_at": "2026-07-20 20:31:50",
                         *         "updated_at": "2026-07-20 20:31:50",
                         *         "auto_create_user": 0,
                         *         "password_login_disabled": 0
                         *       },
                         *       "oidc_enabled": true,
                         *       "managed_fields": [],
                         *       "notes": []
                         *     }
                         */
                        "application/json": {
                            success?: boolean;
                            title?: string;
                            oidc_settings?: {
                                /** @description Provider name (e.g. Authentik). */
                                name?: string;
                                client_id?: string;
                                /** @description Masked secret representation. */
                                client_secret?: string;
                                /** Format: uri */
                                authorization_url?: string;
                                /** Format: uri */
                                token_url?: string;
                                /** Format: uri */
                                user_info_url?: string;
                                /** Format: uri */
                                redirect_url?: string;
                                /** Format: uri */
                                logout_url?: string;
                                /** @description Identifier field (e.g., sub, email). */
                                user_identifier_field?: string;
                                scopes?: string;
                                auth_style?: string;
                                created_at?: string;
                                updated_at?: string;
                                auto_create_user?: number;
                                password_login_disabled?: number;
                            };
                            /** @description True if OIDC oauth is actively enabled. */
                            oidc_enabled?: boolean;
                            /** @description List of fields managed by environment variables. */
                            managed_fields?: string[];
                            notes?: string[];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/set_oidc_settings.php": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Save OIDC Settings
         * @description Update global OpenID Connect configuration parameters. Requires user ID 1 (Admin role).
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/x-www-form-urlencoded": {
                        /** @description The Admin's Wallos API Key. */
                        api_key: string;
                        /**
                         * @description '1' to enable OIDC OAuth 2.0 logins, '0' to disable. (Cannot be modified if set via environment variable).
                         * @enum {integer}
                         */
                        oidc_enabled?: 0 | 1;
                        /** @description OIDC Provider name (e.g. Authentik, Keycloak). */
                        name?: string;
                        /** @description The OIDC client registration ID. */
                        client_id?: string;
                        /** @description The OIDC client credentials secret. */
                        client_secret?: string;
                        /**
                         * Format: uri
                         * @description OIDC authorization URL.
                         */
                        authorization_url?: string;
                        /**
                         * Format: uri
                         * @description OIDC Token Exchange URL (must be public IP/host).
                         */
                        token_url?: string;
                        /**
                         * Format: uri
                         * @description OIDC User Info URL (must be public IP/host).
                         */
                        user_info_url?: string;
                        /**
                         * Format: uri
                         * @description Redirect OIDC Callback URL.
                         */
                        redirect_url?: string;
                        /**
                         * Format: uri
                         * @description Provider session termination URL.
                         */
                        logout_url?: string;
                        /**
                         * @description The claim field containing the unique user identifier.
                         * @default sub
                         */
                        user_identifier_field?: string;
                        /**
                         * @description Request scopes.
                         * @default openid email profile
                         */
                        scopes?: string;
                        /**
                         * @default auto
                         * @enum {string}
                         */
                        auth_style?: "auto" | "header" | "params";
                        /**
                         * @description '1' to automatically create accounts for new users logging in via OIDC.
                         * @enum {integer}
                         */
                        auto_create_user?: 0 | 1;
                        /**
                         * @description '1' to enforce OIDC login and disable local password login.
                         * @enum {integer}
                         */
                        password_login_disabled?: 0 | 1;
                        /**
                         * @description '1' to require OIDC provider email verification flags.
                         * @enum {integer}
                         */
                        require_email_verified?: 0 | 1;
                    };
                };
            };
            responses: {
                /** @description Successful operation. Returns JSON. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description True if settings were successfully written. */
                            success?: boolean;
                            /** @description Brief status title. */
                            title?: string;
                            /** @description Description of the result or error. */
                            message?: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/categories/get_categories.php": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Categories
         * @description Retrieve a list of categories from the Wallos application.
         */
        get: {
            parameters: {
                query: {
                    /** @description API key of the user. */
                    apiKey: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Successful response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description Indicates whether the request was successful. */
                            success?: boolean;
                            /** @description The title of the response. */
                            title?: string;
                            categories?: {
                                /** @description The unique identifier for the category. */
                                id?: number;
                                /** @description The name of the category. */
                                name?: string;
                                /** @description The display order of the category. */
                                order?: number;
                                /** @description Indicates if the category is currently in use. */
                                in_use?: boolean;
                            }[];
                            /** @description Warning messages or additional information. */
                            notes?: string[];
                        };
                    };
                };
                /** @description Unauthorized - Invalid API Key */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example false */
                            success?: boolean;
                            /** @example Unauthorized */
                            title?: string;
                            /**
                             * @example [
                             *       "Invalid API Key"
                             *     ]
                             */
                            notes?: string[];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/categories/set_categories.php": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Add, Edit, or Delete Categories
         * @description Perform write actions (add, edit, delete) on user categories.
         *
         *     ### Security & Rules
         *     1. **Method Restriction**: Restricts all requests to the `POST` method only.
         *     2. **API Key Authentication**: Verifies `api_key` or `apiKey` against the users database. Returns `401 Unauthorized` if invalid/missing.
         *     3. **Resource Ownership**: Verifies that the target category belongs to the authenticated user.
         *     4. **Input Sanitization**: Cleans category names using the helper validation library.
         *     5. **Add Action**: Requires non-empty name, automatically calculates the next display order.
         *     6. **Edit Action**: Edits the category name. Accepts `id` or `categoryId`.
         *     7. **Delete Action**: Blocks deletion of the default category `1` ("General"). Verifies ownership. Ensures category is not currently in use by any subscriptions before deletion.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @description API key of the user (alternative to `apiKey`). */
                        api_key?: string;
                        /** @description API key of the user (alternative to `api_key`). */
                        apiKey?: string;
                        /**
                         * @description Action to perform on the categories.
                         * @enum {string}
                         */
                        action: "add" | "edit" | "delete";
                        /** @description The unique identifier for the category (required for `edit` and `delete`). */
                        id?: number;
                        /** @description Alternative unique identifier for the category (can be used in `edit` action). */
                        categoryId?: number;
                        /** @description The name of the category (required for `add` and `edit`). */
                        name?: string;
                    };
                };
            };
            responses: {
                /** @description Successful operation */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description Indicates if the request was successful. */
                            success?: boolean;
                            /** @description Title of the response status. */
                            title?: string;
                            /** @description Descriptive message about the result. */
                            message?: string;
                            /** @description The unique identifier of the category (returned only for `add` action). */
                            categoryId?: number;
                        };
                    };
                };
                /** @description Bad Request - Validation or rule constraint violations */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example false */
                            success?: boolean;
                            /** @example Error */
                            title?: string;
                            /**
                             * @example [
                             *       "Category name cannot be empty.",
                             *       "Cannot delete the default category.",
                             *       "Category is in use by subscriptions."
                             *     ]
                             */
                            notes?: string[];
                        };
                    };
                };
                /** @description Unauthorized - Invalid or missing API Key */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example false */
                            success?: boolean;
                            /** @example Unauthorized */
                            title?: string;
                            /**
                             * @example [
                             *       "Invalid API Key"
                             *     ]
                             */
                            notes?: string[];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/currencies/get_currencies.php": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Currencies
         * @description Retrieve a list of currencies and the main currency of the user.
         */
        get: {
            parameters: {
                query: {
                    /** @description API key of the user. */
                    apiKey: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Successful response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description Indicates whether the request was successful. */
                            success?: boolean;
                            /** @description The title of the response. */
                            title?: string;
                            /** @description The ID of the main currency of the user. */
                            main_currency?: number;
                            currencies?: {
                                /** @description The unique identifier for the currency. */
                                id?: number;
                                /** @description The name of the currency. */
                                name?: string;
                                /** @description The symbol of the currency. */
                                symbol?: string;
                                /** @description The ISO code of the currency. */
                                code?: string;
                                /** @description The current exchange rate of the currency. */
                                rate?: string;
                                /** @description Indicates if the currency is currently in use. */
                                in_use?: boolean;
                            }[];
                            /** @description Warning messages or additional information. */
                            notes?: string[];
                        };
                    };
                };
                /** @description Unauthorized - Invalid API Key */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example false */
                            success?: boolean;
                            /** @example Unauthorized */
                            title?: string;
                            /**
                             * @example [
                             *       "Invalid API Key"
                             *     ]
                             */
                            notes?: string[];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/currencies/set_currencies.php": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Add, Edit, or Delete Currencies
         * @description Performs write operations on currencies for the authenticated user.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/x-www-form-urlencoded": {
                        /** @description The user's API Key. */
                        api_key: string;
                        /**
                         * @description The write action to perform.
                         * @enum {string}
                         */
                        action: "add" | "edit" | "delete";
                        /** @description The name of the currency (e.g., Colombian Peso). Required for 'add' and 'edit'. */
                        name?: string;
                        /** @description The currency symbol (e.g., $, €). Required for 'add' and 'edit'. */
                        symbol?: string;
                        /** @description The 3-letter currency code (e.g., COP, EUR). Required for 'add' and 'edit'. */
                        code?: string;
                        /**
                         * Format: float
                         * @description The exchange rate of the currency. Optional; defaults to 1.0 on 'add', only updated if provided on 'edit'.
                         */
                        rate?: number;
                        /** @description The ID of the currency. Required for 'edit' and 'delete' (can also use 'currencyId'). */
                        id?: number;
                        /** @description Alias of 'id'. Required for 'edit' and 'delete'. */
                        currencyId?: number;
                    };
                };
            };
            responses: {
                /** @description Successful operation. Returns JSON. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description True if the operation succeeded, false otherwise. */
                            success?: boolean;
                            /** @description Brief status title. */
                            title?: string;
                            /** @description Description of the result or error. */
                            message?: string;
                            /** @description The ID of the newly added currency. Only returned for successful 'add' action. */
                            currencyId?: number;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/fixer/get_fixer.php": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Fixer Settings
         * @description Retrieve the Fixer settings for the user.
         */
        get: {
            parameters: {
                query: {
                    /** @description API key of the user. */
                    api_key: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Successful response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description Indicates whether the request was successful. */
                            success?: boolean;
                            /** @description The title of the response. */
                            title?: string;
                            fixer?: {
                                /** @description The API key used for accessing Fixer. */
                                api_key?: string;
                                /** @description The ID of the provider. */
                                provider?: number;
                                /** @description The name of the provider. */
                                provider_name?: string;
                            };
                            /** @description Warning messages or additional information. */
                            notes?: string[];
                        };
                    };
                };
                /** @description Unauthorized - Invalid API Key */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example false */
                            success?: boolean;
                            /** @example Unauthorized */
                            title?: string;
                            /**
                             * @example [
                             *       "Invalid API Key"
                             *     ]
                             */
                            notes?: string[];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/fixer/set_fixer.php": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Save or Clear Fixer API settings
         * @description Saves and verifies Fixer.io or APILayer API keys, or clears them.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/x-www-form-urlencoded": {
                        /** @description The user's Wallos API Key. */
                        api_key: string;
                        /** @description The Fixer.io or APILayer API Key. Leave empty to clear/delete settings. */
                        fixer_api_key?: string;
                        /**
                         * @description '0' for Fixer.io, '1' for APILayer.com.
                         * @default 0
                         * @enum {integer}
                         */
                        provider?: 0 | 1;
                    };
                };
            };
            responses: {
                /** @description Successful operation. Returns JSON. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description True if the operation succeeded, false otherwise. */
                            success?: boolean;
                            /** @description Brief status title. */
                            title?: string;
                            /** @description Description of the result or error. */
                            message?: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/household/get_household.php": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Household
         * @description Retrieve the household members.
         */
        get: {
            parameters: {
                query: {
                    apiKey: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Successful response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success?: boolean;
                            title?: string;
                            household?: {
                                id?: number;
                                name?: string;
                                email?: string;
                                in_use?: boolean;
                            }[];
                            notes?: string[];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/household/set_household.php": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Add, Edit, or Delete Household Members
         * @description Performs write operations on household members for the authenticated user.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/x-www-form-urlencoded": {
                        /** @description The user's Wallos API Key. */
                        api_key: string;
                        /**
                         * @description The write action to perform.
                         * @enum {string}
                         */
                        action: "add" | "edit" | "delete";
                        /** @description The name of the household member. Required for 'add' and 'edit'. */
                        name?: string;
                        /** @description The email of the household member. Optional; can be updated to empty. */
                        email?: string;
                        /** @description The ID of the household member. Required for 'edit' and 'delete' (can also use 'memberId'). */
                        id?: number;
                        /** @description Alias of 'id'. Required for 'edit' and 'delete'. */
                        memberId?: number;
                    };
                };
            };
            responses: {
                /** @description Successful operation. Returns JSON. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description True if the operation succeeded, false otherwise. */
                            success?: boolean;
                            /** @description Brief status title. */
                            title?: string;
                            /** @description Description of the result or error. */
                            message?: string;
                            /** @description The ID of the newly added household member. Only returned for successful 'add' action. */
                            memberId?: number;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notifications/get_notification_settings.php": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Notification Settings
         * @description Retrieve the notification setup and active channels (SMTP/Email, Discord, Gotify, Ntfy, Pushover, Telegram, Webhook, and Serverchan) for the authenticated user.
         */
        get: {
            parameters: {
                query: {
                    /** @description The user's Wallos API Key. */
                    api_key: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Successful retrieval of the notification settings. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success?: boolean;
                            title?: string;
                            notification_settings?: {
                                id?: number;
                                /** @description Default reminder offset in days before the billing date. */
                                days?: number;
                                email_notifications?: {
                                    enabled?: number;
                                    smtp_address?: string;
                                    smtp_port?: number;
                                    smtp_username?: string;
                                    /** @description Masked value. */
                                    smtp_password?: string;
                                    from_email?: string;
                                    encryption?: string;
                                    other_emails?: string;
                                } | null;
                                discord_notifications?: {
                                    enabled?: number;
                                    webhook_url?: string;
                                } | null;
                                gotify_notifications?: {
                                    enabled?: number;
                                    host?: string;
                                    /** @description Masked value. */
                                    token?: string;
                                    priority?: number;
                                } | null;
                                ntfy_notifications?: {
                                    enabled?: number;
                                    host?: string;
                                    topic?: string;
                                    /** @description Masked value. */
                                    headers?: string;
                                    priority?: number;
                                } | null;
                                pushover_notifications?: {
                                    enabled?: number;
                                    /** @description Masked value. */
                                    token?: string;
                                    user_key?: string;
                                    title?: string;
                                    priority?: number;
                                    sound?: string;
                                } | null;
                                telegram_notifications?: {
                                    enabled?: number;
                                    /** @description Masked value. */
                                    bot_token?: string;
                                    chat_id?: string;
                                } | null;
                                webhook_notifications?: {
                                    enabled?: number;
                                    url?: string;
                                    /** @description Masked value. */
                                    headers?: string;
                                } | null;
                                serverchan_notifications?: {
                                    enabled?: number;
                                    /** @description Masked value. */
                                    sendkey?: string;
                                } | null;
                            };
                            notes?: string[];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/payment_methods/get_payment_methods.php": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Payment Methods
         * @description Retrieve the available payment methods.
         */
        get: {
            parameters: {
                query: {
                    api_key: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Successful response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success?: boolean;
                            title?: string;
                            payment_methods?: {
                                id?: number;
                                name?: string;
                                icon?: string;
                                enabled?: number;
                                order?: number;
                                in_use?: boolean;
                            }[];
                            notes?: string[];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/payment_methods/set_payment_methods.php": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Add, Edit, or Delete Payment Methods
         * @description Performs write operations on payment methods for the authenticated user, supporting icon URL fetches and multipart file uploads.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "multipart/form-data": {
                        /** @description The user's Wallos API Key. */
                        api_key: string;
                        /**
                         * @description The write action to perform.
                         * @enum {string}
                         */
                        action: "add" | "edit" | "delete";
                        /** @description The name of the payment method. Required for 'add', optional for 'edit'. */
                        name?: string;
                        /**
                         * @description '1' for active, '0' for inactive.
                         * @default 1
                         * @enum {string}
                         */
                        enabled?: "0" | "1";
                        /** @description An image URL to fetch as the icon (e.g. from Clearbit). */
                        icon_url?: string;
                        /**
                         * Format: binary
                         * @description Direct file upload of an image to use as the icon.
                         */
                        paymenticon?: string;
                        /** @description The ID of the payment method. Required for 'edit' and 'delete' (can also use 'paymentId'). */
                        id?: number;
                        /** @description Alias of 'id'. Required for 'edit' and 'delete'. */
                        paymentId?: number;
                    };
                };
            };
            responses: {
                /** @description Successful operation. Returns JSON. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description True if the operation succeeded, false otherwise. */
                            success?: boolean;
                            /** @description Brief status title. */
                            title?: string;
                            /** @description Description of the result or error. */
                            message?: string;
                            /** @description The ID of the newly added payment method. Only returned for successful 'add' action. */
                            paymentId?: number;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings/get_settings.php": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get User Settings
         * @description Retrieve the user settings.
         */
        get: {
            parameters: {
                query: {
                    api_key: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Successful response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success?: boolean;
                            title?: string;
                            settings?: {
                                dark_theme?: number;
                                monthly_price?: number;
                                convert_currency?: number;
                                remove_background?: number;
                                color_theme?: string;
                                hide_disabled?: number;
                                disabled_to_bottom?: number;
                                show_original_price?: number;
                                mobile_nav?: number;
                                custom_css?: {
                                    css?: string;
                                };
                                /** @description Indicates if subscription progress is shown (1 for true, 0 for false). */
                                show_subscription_progress?: number;
                                /** @description Indicates if the week starts on Sunday (1 for true, 0 for false). */
                                week_starts_sunday?: number;
                                custom_colors?: {
                                    /** @description The unique row ID of the custom colors. */
                                    id?: number;
                                    /** @description The main color in hex format. */
                                    main_color?: string;
                                    /** @description The accent color in hex format. */
                                    accent_color?: string;
                                    /** @description The hover color in hex format. */
                                    hover_color?: string;
                                };
                            };
                            notes?: string[];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings/set_settings.php": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Save User Settings
         * @description Updates any visual, theme, custom color, custom CSS, or layout preference toggles for the authenticated user.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/x-www-form-urlencoded": {
                        /** @description The user's Wallos API Key. */
                        api_key: string;
                        /**
                         * @description '0' for light theme, '1' for dark theme, '2' for automatic theme.
                         * @enum {integer}
                         */
                        dark_theme?: 0 | 1 | 2;
                        /**
                         * @description The overall color scheme.
                         * @enum {string}
                         */
                        color_theme?: "blue" | "green" | "red" | "yellow" | "purple" | "custom";
                        /**
                         * @description '1' to show monthly prices, '0' to show full interval price.
                         * @enum {string}
                         */
                        monthly_price?: "0" | "1";
                        /**
                         * @description '1' to convert prices to the primary currency, '0' to show original currency.
                         * @enum {string}
                         */
                        convert_currency?: "0" | "1";
                        /**
                         * @description '1' to show original prices next to converted ones, '0' to hide.
                         * @enum {string}
                         */
                        show_original_price?: "0" | "1";
                        /**
                         * @description '1' to show bottom navigation menu on mobile, '0' to show sidebar.
                         * @enum {string}
                         */
                        mobile_nav?: "0" | "1";
                        /**
                         * @description '1' to show active subscription progress bar, '0' to hide.
                         * @enum {string}
                         */
                        show_subscription_progress?: "0" | "1";
                        /**
                         * @description '1' to start calendar weeks on Sunday, '0' to start on Monday.
                         * @enum {string}
                         */
                        week_starts_sunday?: "0" | "1";
                        /**
                         * @description '1' to push inactive subscriptions to the bottom of the list, '0' to keep sorted.
                         * @enum {string}
                         */
                        disabled_to_bottom?: "0" | "1";
                        /**
                         * @description '1' to hide disabled subscriptions entirely from the dashboard, '0' to show.
                         * @enum {string}
                         */
                        hide_disabled?: "0" | "1";
                        /**
                         * @description '1' to remove white background from uploaded logos, '0' to keep as-is.
                         * @enum {string}
                         */
                        remove_background?: "0" | "1";
                        /** @description Hex code (e.g., */
                        main_color?: string;
                        /** @description Hex code (e.g., */
                        accent_color?: string;
                        /** @description Hex code (e.g., */
                        hover_color?: string;
                        /** @description Custom CSS code rules to load into the web interface. */
                        css?: string;
                    };
                };
            };
            responses: {
                /** @description Successful settings update. Returns JSON. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description True if the operation succeeded, false otherwise. */
                            success?: boolean;
                            /** @description Brief status title. */
                            title?: string;
                            /** @description Description of the result or error. */
                            message?: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/subscriptions/get_ical_feed.php": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Subscription iCal Feed
         * @description Generates a standard iCal calendar file containing events for all active subscriptions and their renewal dates.
         */
        get: {
            parameters: {
                query: {
                    /** @description The user's Wallos API Key (can also use 'apiKey'). */
                    api_key: string;
                    /** @description If true, converts subscription prices to the primary currency in the event descriptions. */
                    convert_currency?: "true" | "false";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description A downloadable iCal file (.ics). */
                200: {
                    headers: {
                        "Content-Disposition"?: string;
                        [name: string]: unknown;
                    };
                    content: {
                        "text/calendar": string;
                    };
                };
                /** @description Unauthorized - Invalid API Key */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example false */
                            success?: boolean;
                            /** @example Unauthorized */
                            title?: string;
                            /**
                             * @example [
                             *       "Invalid API Key"
                             *     ]
                             */
                            notes?: string[];
                        };
                    };
                };
            };
        };
        put?: never;
        /**
         * Get Subscription iCal Feed (POST method)
         * @description Generates a standard iCal calendar file containing events for all active subscriptions and their renewal dates using POST request parameters.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/x-www-form-urlencoded": {
                        /** @description The user's Wallos API Key (can also use 'apiKey'). */
                        api_key: string;
                        /**
                         * @description If true, converts subscription prices to the primary currency in the event descriptions.
                         * @enum {string}
                         */
                        convert_currency?: "true" | "false";
                    };
                };
            };
            responses: {
                /** @description A downloadable iCal file (.ics). */
                200: {
                    headers: {
                        "Content-Disposition"?: string;
                        [name: string]: unknown;
                    };
                    content: {
                        "text/calendar": string;
                    };
                };
                /** @description Unauthorized - Invalid API Key */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example false */
                            success?: boolean;
                            /** @example Unauthorized */
                            title?: string;
                            /**
                             * @example [
                             *       "Invalid API Key"
                             *     ]
                             */
                            notes?: string[];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/subscriptions/get_monthly_cost.php": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Monthly Cost
         * @description Retrieve the total cost of subscriptions for a specific month and year.
         */
        get: {
            parameters: {
                query: {
                    /** @description The API key of the user. */
                    apiKey: string;
                    /** @description The month for which the cost is to be calculated. */
                    month: number;
                    /** @description The year for which the cost is to be calculated. */
                    year: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Successful response with monthly cost details. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description Whether the request was successful. */
                            success?: boolean;
                            /** @description A string representing the month and year (e.g., March 2025). */
                            title?: string;
                            /**
                             * Format: float
                             * @description The total cost for the specified month.
                             */
                            monthly_cost?: number;
                            /** @description The total cost formatted according to the user's locale and currency. */
                            localized_monthly_cost?: string;
                            /** @description The currency code of the user's main currency. */
                            currency_code?: string;
                            /** @description The currency symbol of the user's main currency. */
                            currency_symbol?: string;
                            /** @description Warning messages or additional information. */
                            notes?: string[];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/subscriptions/get_subscription.php": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Single Subscription
         * @description Retrieve detailed information for a single subscription by its ID.
         */
        get: {
            parameters: {
                query: {
                    /** @description The user's Wallos API Key (can also be passed as 'apiKey'). */
                    api_key: string;
                    /** @description The ID of the subscription to retrieve (can also use 'subscription_id'). */
                    id: number;
                    /** @description If true, converts the price to the user's main currency. */
                    convert_currency?: "true" | "false";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Successful retrieval of the subscription. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success?: boolean;
                            title?: string;
                            subscription?: {
                                id?: number;
                                name?: string;
                                logo?: string;
                                price?: number;
                                currency_id?: number;
                                start_date?: string;
                                next_payment?: string;
                                cycle?: number;
                                frequency?: number;
                                auto_renew?: number;
                                notes?: string;
                                payment_method_id?: number;
                                payer_user_id?: number;
                                category_id?: number;
                                notify?: number;
                                url?: string;
                                inactive?: number;
                                notify_days_before?: number;
                                user_id?: number;
                                category_name?: string;
                                payer_user_name?: string;
                                payment_method_name?: string;
                            };
                            notes?: string[];
                        };
                    };
                };
            };
        };
        put?: never;
        /**
         * Get Single Subscription (POST method)
         * @description Retrieve detailed information for a single subscription using POST request parameters.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/x-www-form-urlencoded": {
                        /** @description The user's Wallos API Key. */
                        api_key: string;
                        /** @description The ID of the subscription to retrieve. */
                        id: number;
                        /**
                         * @description If true, converts the price to the user's main currency.
                         * @enum {string}
                         */
                        convert_currency?: "true" | "false";
                    };
                };
            };
            responses: {
                /** @description Successful retrieval. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success?: boolean;
                            title?: string;
                            subscription?: {
                                id?: number;
                                name?: string;
                                logo?: string;
                                price?: number;
                                currency_id?: number;
                                start_date?: string;
                                next_payment?: string;
                                cycle?: number;
                                frequency?: number;
                                auto_renew?: number;
                                notes?: string;
                                payment_method_id?: number;
                                payer_user_id?: number;
                                category_id?: number;
                                notify?: number;
                                url?: string;
                                inactive?: number;
                                notify_days_before?: number;
                                user_id?: number;
                                category_name?: string;
                                payer_user_name?: string;
                                payment_method_name?: string;
                            };
                            notes?: string[];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/subscriptions/get_subscriptions.php": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Subscriptions
         * @description Retrieve a list of subscriptions with optional filters.
         */
        get: {
            parameters: {
                query: {
                    /** @description The API key of the user. */
                    apiKey: string;
                    /** @description Comma-separated IDs of the members to filter. */
                    member?: string;
                    /** @description The ID of the category to filter. */
                    category?: number;
                    /** @description The ID of the payment method to filter. */
                    payment_method?: number;
                    /** @description The state of the subscription to filter [0 - active, 1 - inactive]. */
                    state?: boolean;
                    /** @description Whether to sort inactive subscriptions to the bottom. */
                    disabled_to_bottom?: boolean;
                    /**
                     * @description The sorting method ['name', 'id', 'next_payment', 'price', etc.].
                     * @default next_payment
                     */
                    sort?: "name" | "id" | "next_payment" | "price" | "payer_user_id" | "category_id" | "payment_method_id" | "inactive" | "alphanumeric";
                    /**
                     * @description Whether to convert the prices to the main currency.
                     * @default false
                     */
                    convert_currency?: boolean;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Successful response with subscription details. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description Whether the request was successful. */
                            success?: boolean;
                            /** @description The title of the response, typically 'subscriptions'. */
                            title?: string;
                            subscriptions?: {
                                id?: number;
                                name?: string;
                                logo?: string;
                                /** Format: float */
                                price?: number;
                                currency_id?: number;
                                /** Format: date */
                                next_payment?: string;
                                cycle?: number;
                                frequency?: number;
                                notes?: string;
                                payment_method_id?: number;
                                payer_user_id?: number;
                                category_id?: number;
                                notify?: boolean;
                                url?: string;
                                inactive?: boolean;
                                notify_days_before?: number;
                                /** Format: date */
                                cancelation_date?: string;
                                category_name?: string;
                                payer_user_name?: string;
                                payment_method_name?: string;
                            }[];
                            /** @description Warning messages or additional information. */
                            notes?: string[];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/subscriptions/set_subscriptions.php": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Add, Edit, or Delete Subscriptions
         * @description Performs write operations on subscriptions for the authenticated user, supporting optional logo downloads and file uploads.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "multipart/form-data": {
                        /** @description The user's Wallos API Key. */
                        api_key: string;
                        /**
                         * @description The write action to perform.
                         * @enum {string}
                         */
                        action: "add" | "edit" | "delete";
                        /** @description The ID of the subscription. Required for 'edit' and 'delete' (can also use 'subscription_id' or 'subscriptionId'). */
                        id?: number;
                        /** @description The name of the subscription. Required for 'add', optional for 'edit'. */
                        name?: string;
                        /**
                         * Format: float
                         * @description The subscription price. Required for 'add', optional for 'edit'.
                         */
                        price?: number;
                        /** @description The currency ID. Required for 'add', optional for 'edit'. */
                        currency_id?: number;
                        /** @description The payment frequency. Required for 'add', optional for 'edit'. */
                        frequency?: number;
                        /**
                         * @description '1' for Days, '2' for Weeks, '3' for Months, '4' for Years. Required for 'add', optional for 'edit'.
                         * @enum {integer}
                         */
                        cycle?: 1 | 2 | 3 | 4;
                        /**
                         * Format: date
                         * @description The date of the next payment (YYYY-MM-DD). Required for 'add', optional for 'edit'.
                         */
                        next_payment?: string;
                        /**
                         * Format: date
                         * @description The subscription start date (YYYY-MM-DD). Optional.
                         */
                        start_date?: string;
                        /**
                         * @description '1' for auto-renew enabled, '0' otherwise. Optional.
                         * @default 1
                         * @enum {string}
                         */
                        auto_renew?: "0" | "1";
                        /** @description The payment method ID. Optional. */
                        payment_method_id?: number;
                        /** @description The household member ID of the payer. Optional. */
                        payer_user_id?: number;
                        /** @description The category ID. Optional. */
                        category_id?: number;
                        /** @description Custom notes. Optional. */
                        notes?: string;
                        /** @description Subscription URL. Optional. */
                        url?: string;
                        /** @description An image URL to download as the logo. Optional. */
                        logo_url?: string;
                        /**
                         * Format: binary
                         * @description Direct file upload of an image to use as the logo. Optional.
                         */
                        logo?: string;
                        /**
                         * @description '1' to enable payment notifications (can also use 'notifications'). Optional.
                         * @enum {string}
                         */
                        notify?: "0" | "1";
                        /** @description Days before the next payment to notify. Optional. */
                        notify_days_before?: number;
                        /**
                         * @description '1' if the subscription is inactive/canceled. Optional.
                         * @enum {string}
                         */
                        inactive?: "0" | "1";
                        /**
                         * Format: date
                         * @description Date of subscription cancellation (YYYY-MM-DD). Optional.
                         */
                        cancellation_date?: string;
                        /** @description The ID of the subscription replacing this one. Optional. */
                        replacement_subscription_id?: number;
                    };
                };
            };
            responses: {
                /** @description Successful operation. Returns JSON. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description True if the operation succeeded, false otherwise. */
                            success?: boolean;
                            /** @description Brief status title. */
                            title?: string;
                            /** @description Description of the result or error. */
                            message?: string;
                            /** @description The ID of the newly added subscription. Only returned for successful 'add' action. */
                            subscriptionId?: number;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/get_user.php": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get User Details
         * @description Retrieve profile details, main currency, language, and budget settings for the authenticated user.
         */
        get: {
            parameters: {
                query: {
                    /** @description The user's Wallos API Key (can also use 'apiKey'). */
                    api_key: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Successful retrieval of the user profile. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "success": true,
                         *       "title": "user",
                         *       "user": {
                         *         "id": 1,
                         *         "username": "johndoe",
                         *         "email": "john.doe@example.com",
                         *         "password": "********",
                         *         "main_currency": 1,
                         *         "avatar": "images/uploads/logos/avatars/default-avatar.jpg",
                         *         "language": "en",
                         *         "budget": 200,
                         *         "totp_enabled": 0,
                         *         "api_key": "********",
                         *         "firstname": "John",
                         *         "lastname": "Doe"
                         *       },
                         *       "notes": []
                         *     }
                         */
                        "application/json": {
                            success?: boolean;
                            title?: string;
                            user?: {
                                id?: number;
                                username?: string;
                                /** Format: email */
                                email?: string;
                                /** @description Always returned as "********" for security. */
                                password?: string;
                                /** @description The ID of the user's primary currency. */
                                main_currency?: number;
                                /** @description Path to the user avatar image. */
                                avatar?: string;
                                /** @description The selected UI language code (e.g., "en"). */
                                language?: string;
                                /** @description The user's configured monthly budget limit. */
                                budget?: number;
                                /** @description 1 if Two-Factor Authentication (TOTP) is enabled, 0 otherwise. */
                                totp_enabled?: number;
                                /** @description Always returned as "********" for security. */
                                api_key?: string;
                                firstname?: string;
                                lastname?: string;
                            };
                            notes?: string[];
                        };
                    };
                };
            };
        };
        put?: never;
        /**
         * Get User Details (POST method)
         * @description Retrieve profile details, main currency, language, and budget settings using POST request parameters.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/x-www-form-urlencoded": {
                        /** @description The user's Wallos API Key (can also use 'apiKey'). */
                        api_key: string;
                    };
                };
            };
            responses: {
                /** @description Successful retrieval of the user profile. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "success": true,
                         *       "title": "user",
                         *       "user": {
                         *         "id": 1,
                         *         "username": "johndoe",
                         *         "email": "john.doe@example.com",
                         *         "password": "********",
                         *         "main_currency": 1,
                         *         "avatar": "images/uploads/logos/avatars/default-avatar.jpg",
                         *         "language": "en",
                         *         "budget": 200,
                         *         "totp_enabled": 0,
                         *         "api_key": "********",
                         *         "firstname": "John",
                         *         "lastname": "Doe"
                         *       },
                         *       "notes": []
                         *     }
                         */
                        "application/json": {
                            success?: boolean;
                            title?: string;
                            user?: {
                                id?: number;
                                username?: string;
                                /** Format: email */
                                email?: string;
                                /** @description Always returned as "********" for security. */
                                password?: string;
                                /** @description The ID of the user's primary currency. */
                                main_currency?: number;
                                /** @description Path to the user avatar image. */
                                avatar?: string;
                                /** @description The selected UI language code (e.g., "en"). */
                                language?: string;
                                /** @description The user's configured monthly budget limit. */
                                budget?: number;
                                /** @description 1 if Two-Factor Authentication (TOTP) is enabled, 0 otherwise. */
                                totp_enabled?: number;
                                /** @description Always returned as "********" for security. */
                                api_key?: string;
                                firstname?: string;
                                lastname?: string;
                            };
                            notes?: string[];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: never;
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
